name: Dispatch Update Submodule
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"
      - name: Dispatch update to ssm-client Project
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: oblitorum/parent
          event-type: update-submodule
          client-payload: '{"repo": "submodule-1", "commit_message": "${{ env.COMMIT_MESSAGE }}"}'
